services:
  db:
     image: mysql:latest
     environment:
        MYSQL_DATABASE: api_db
        MYSQL_USER: api_db_user
        MYSQL_PASSWORD: Seyla758@ 
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
     volumes:
      - "./db:/docker-entrypoint-initdb.d"
     networks:
      - api_db_user
  www:
     depends_on:
      - db
     build:
      context: .
      dockerfile: Dockerfile
     volumes:
      - "./:/var/www/html"
     ports:
      - 80:80
      - 443:443
     networks:
      - api_db_user
  phpmyadmin:
     depends_on:
      - db
     image: phpmyadmin/phpmyadmin
     ports:
      - 8081:80
     environment:
      - PMA_HOST=db
      - PMA_PORT=3306
     networks:
      - api_db_user
networks:
   api_db_user:
    driver: bridge